{
 "title": "DevSecOps Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "prometheus_http_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "prometheus_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "scrape_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  }
 ]
}